// Conversion semantics adapted from protobufjs. See LICENSE-protobufjs.
import protobuf from 'protobufjs/minimal.js'

const { util } = protobuf
const skip = Symbol('unassigned protobuf field')
const hasOwn = (value, key) => Object.prototype.hasOwnProperty.call(value, key)

// A field is [name, scalar name | message constructor | enum, collection?, oneof?].
// Wire encoding/decoding remains generated by protobufjs. Object conversion and
// small message helpers share implementations instead of repeating their branches.
function fromValue(value, type, path, repeated, depth) {
	if (typeof type === 'function') {
		if (typeof value !== 'object') throw TypeError(path + ': object expected')
		return type.fromObject(value, depth + 1)
	}
	if (typeof type === 'object') {
		if (typeof value === 'number') return value
		if (typeof value === 'string' && hasOwn(type, value) && typeof type[value] === 'number') return type[value]
		return repeated ? Object.values(type).find(item => typeof item === 'number') : skip
	}
	switch (type) {
		case 'double':
		case 'float':
			return Number(value)
		case 'uint32':
		case 'fixed32':
			return value >>> 0
		case 'int32':
		case 'sint32':
		case 'sfixed32':
			return value | 0
		case 'uint64':
		case 'int64':
		case 'sint64':
		case 'fixed64':
		case 'sfixed64': {
			const unsigned = type === 'uint64'
			if (util.Long) {
				const result = util.Long.fromValue(value)
				result.unsigned = unsigned
				return result
			}
			if (typeof value === 'string') return parseInt(value, 10)
			if (typeof value === 'number') return value
			if (typeof value === 'object') return new util.LongBits(value.low >>> 0, value.high >>> 0).toNumber(unsigned)
			return skip
		}
		case 'bytes':
			if (typeof value === 'string') {
				const buffer = util.newBuffer(util.base64.length(value))
				util.base64.decode(value, buffer, 0)
				return buffer
			}
			return value.length >= 0 ? value : skip
		case 'string':
			return String(value)
		case 'bool':
			return Boolean(value)
		default:
			throw Error('Unsupported protobuf scalar: ' + type)
	}
}

function longToString(value, unsigned) {
	if (typeof value === 'string') return value
	if (typeof value === 'number') return String(value)
	if (value && typeof value.low === 'number' && typeof value.high === 'number') {
		const combined = (BigInt(value.high >>> 0) << 32n) | BigInt(value.low >>> 0)
		return (!unsigned && value.high < 0 ? combined - (1n << 64n) : combined).toString()
	}
	return String(value)
}

function longToNumber(value, unsigned) {
	if (typeof value === 'number') return value
	if (typeof value === 'string') return Number(value)
	if (value && typeof value.low === 'number' && typeof value.high === 'number') {
		const combined = (BigInt(value.high >>> 0) << 32n) | BigInt(value.low >>> 0)
		return Number(!unsigned && value.high < 0 ? combined - (1n << 64n) : combined)
	}
	return Number(value)
}

function toValue(value, type, options) {
	if (typeof type === 'function') return type.toObject(value, options)
	if (typeof type === 'object') return options.enums === String && type[value] !== undefined ? type[value] : value
	switch (type) {
		case 'double':
		case 'float':
			return options.json && !isFinite(value) ? String(value) : value
		case 'uint64':
		case 'int64':
		case 'sint64':
		case 'fixed64':
		case 'sfixed64':
			if (typeof value === 'number') return options.longs === String ? String(value) : value
			if (options.longs === String) return longToString(value, type === 'uint64')
			if (options.longs === Number) return longToNumber(value, type === 'uint64')
			return value
		case 'bytes':
			if (options.bytes === String) return util.base64.encode(value, 0, value.length)
			if (options.bytes === Array) return Array.prototype.slice.call(value)
			return value
		default:
			return value
	}
}

function defaultValue(value, type, options) {
	if (typeof type === 'function') return null
	if (typeof type === 'object') return options.enums === String ? type[value] : value
	if (['uint64', 'int64', 'sint64', 'fixed64', 'sfixed64'].includes(type)) {
		if (util.Long) {
			const result = new util.Long(value.low, value.high, value.unsigned)
			if (options.longs === String) return result.toString()
			if (options.longs === Number) return result.toNumber()
			return result
		}
		return options.longs === String ? longToString(value, type === 'uint64') : longToNumber(value, type === 'uint64')
	}
	if (type === 'bytes') {
		if (options.bytes === String) return String.fromCharCode(...value)
		const result = Array.prototype.slice.call(value)
		return options.bytes === Array ? result : util.newBuffer(result)
	}
	return value
}

function toJSON() {
	return this.constructor.toObject(this, util.toJSONOptions)
}

// Registration-time caches are released after all types have been initialized.
// A single-field oneof needs only its field name, not protobufjs's array and map.
export function installMessageHelpers(definitions) {
	const optionalAccessors = new Map()
	for (const [Message, name, fields, fieldOrder] of definitions) {
		const oneofs = new Map()
		for (const [key, , , oneof] of fields) {
			if (!oneof) continue
			if (!oneofs.has(oneof)) oneofs.set(oneof, [])
			oneofs.get(oneof).push(key)
		}
		for (const [oneof, keys] of oneofs) {
			let descriptor
			if (keys.length === 1) {
				const key = keys[0]
				descriptor = optionalAccessors.get(key)
				if (!descriptor) {
					descriptor = {
						get() {
							if (Object.prototype.propertyIsEnumerable.call(this, key) && this[key] != null) return key
						},
						set(value) {
							if (value !== key) delete this[key]
						}
					}
					optionalAccessors.set(key, descriptor)
				}
			} else {
				descriptor = { get: util.oneOfGetter(keys), set: util.oneOfSetter(keys) }
			}
			Object.defineProperty(Message.prototype, oneof, descriptor)
		}
		installConversions(Message, name, fields, fieldOrder)
	}
}

function installConversions(Message, name, fields, fieldOrder) {
	const orderedFields = fieldOrder ? fieldOrder.map(index => fields[index]) : fields
	Message.create = function create(properties) {
		return new Message(properties)
	}
	Message.getTypeUrl = function getTypeUrl(prefix) {
		if (prefix === undefined) prefix = 'type.googleapis.com'
		return prefix + '/' + name
	}
	Message.fromObject = function fromObject(object, depth = 0) {
		if (object instanceof Message) return object
		if (depth > util.recursionLimit) throw Error('maximum nesting depth exceeded')
		const message = new Message()
		for (const [key, type, collection] of fields) {
			const value = object[key]
			if (collection) {
				if (!value) continue
				const path = '.' + name + '.' + key
				if (collection === 'array' && !Array.isArray(value)) throw TypeError(path + ': array expected')
				if (collection === 'map' && typeof value !== 'object') throw TypeError(path + ': object expected')
				const result = (message[key] = collection === 'array' ? [] : {})
				const keys = collection === 'array' ? Array.prototype.keys.call(value) : Object.keys(value)
				for (const index of keys) {
					if (index === '__proto__') util.makeProp(result, index)
					const converted = fromValue(value[index], type, path, collection === 'array', depth)
					if (converted !== skip) result[index] = converted
				}
			} else if (value != null || typeof type === 'object') {
				const converted = fromValue(value, type, '.' + name + '.' + key, false, depth)
				if (converted !== skip) message[key] = converted
			}
		}
		return message
	}
	Message.toObject = function toObject(message, options) {
		const result = {}
		if (!fields.length) return result
		options ||= {}
		// protobufjs emits empty arrays, then maps, then scalar defaults before
		// populated fields. Preserve that property order for JSON consumers.
		if (options.defaults || options.arrays || options.objects) {
			for (const collection of ['array', 'map', undefined]) {
				if (
					!(options.defaults || (collection === 'array' && options.arrays) || (collection === 'map' && options.objects))
				)
					continue
				for (const [key, type, rule, oneof] of orderedFields) {
					if (rule !== collection || oneof) continue
					result[key] =
						collection === 'array'
							? []
							: collection === 'map'
								? {}
								: defaultValue(Message.prototype[key], type, options)
				}
			}
		}
		for (const [key, type, collection, oneof] of orderedFields) {
			const value = message[key]
			if (collection) {
				if (!value) continue
				const keys = collection === 'array' ? Array.prototype.keys.call(value) : Object.keys(value)
				if (!(collection === 'array' ? value.length : keys.length)) continue
				const target = (result[key] = collection === 'array' ? [] : {})
				for (const index of keys) {
					if (index === '__proto__') util.makeProp(target, index)
					target[index] = toValue(value[index], type, options)
				}
			} else if (value != null && message.hasOwnProperty(key)) {
				result[key] = toValue(value, type, options)
				if (oneof && options.oneofs) result[oneof] = key
			}
		}
		return result
	}
	Message.prototype.toJSON = toJSON
}
